'use strict'; // code generated by pbf v3.2.1

// LikePayId ========================================

var LikePayId = exports.LikePayId = {};

LikePayId.read = function (pbf, end) {
    return pbf.readFields(LikePayId._readField, {uuid: null, address: null, amount: null}, end);
};
LikePayId._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.uuid = pbf.readBytes();
    else if (tag === 2) obj.address = pbf.readBytes();
    else if (tag === 3) obj.amount = pbf.readBytes();
};
LikePayId.write = function (obj, pbf) {
    if (obj.uuid) pbf.writeBytesField(1, obj.uuid);
    if (obj.address) pbf.writeBytesField(2, obj.address);
    if (obj.amount) pbf.writeBytesField(3, obj.amount);
};
